/* GEO-TAG Generator      */
/* auf www.geo-tag.de     */
/* Javascript Funktionen  */
/* (c) 2007 Helmut Karger */
var aa70;var aa41;var aa28;var aa21;var aa30;var aa50;var aa16 = "nix";var aa09 = "nix";var aa23 = 1000000;var aa22 = false;function aa69 (cc, rc, pn, aa54, aa56, lat, lon, dc, order, aa68) {this.cc = cc;this.rc = rc;this.pn = pn;this.aa54 = aa54;this.aa56 = aa56;this.lat = lat;this.lon = lon;this.dc = dc;this.order = order;this.aa68 = aa68;}var aa52 = new aa69("", "", "", "", "", "", "", "", false, false);
function load() {aa70 = new GMap2(document.getElementById("map"));aa70.addControl(new GLargeMapControl());aa70.addControl(new GMapTypeControl());aa70.setCenter(new GLatLng(9.932668, -84.079056), 7);GEvent.addListener(aa70, "click", aa14);aa41 = new GClientGeocoder();aa21 = aa02();aa30 = aa02();aa50 = aa02();aa55 = aa02();document.getElementById("laendercode").value = "";document.getElementById("regionalcode").value = "";document.getElementById("ort").value = "";document.getElementById("address").value = "";document.getElementById("xhtmlcode").value = "";document.getElementById("lati").value = "0";document.getElementById("longi").value = "0";document.georegion.genau.selectedIndex = 0;document.getElementById("dcan").checked = false;document.getElementById("dctitle").value = " ";document.getElementById("dctitle").disabled = true;document.getElementById("dctitle").style.backgroundColor='#c0e1f3';document.getElementById('haddress').innerHTML=aa03;document.getElementById('hgenau').innerHTML=aa47;document.getElementById('hland').innerHTML=aa10;document.getElementById('hregion').innerHTML=aa05;document.getElementById('hort').innerHTML=aa60;document.getElementById('htitel').innerHTML=aa25;document.getElementById('hcode').innerHTML="";aa33();var aa71 = "";if (document.cookie) {var aa40 = document.cookie.indexOf("=") + 1;var aa48 = document.cookie.indexOf(";");if (aa48 == -1) {aa48 = document.cookie.length;}aa71 = document.cookie.substring(aa40, aa48);aa71 = aa71.split('+').join('%20');aa71 = unescape(aa71);aa71 = aa71.substring(1, aa71.length-1);var aa67 = aa71.split('";"');aa52.lat = aa67[0];aa52.aa54 = aa67[0];aa52.lon = aa67[1];aa52.aa56 = aa67[1];aa52.cc = aa67[2];aa52.rc = aa67[3];aa52.pn = aa67[4];aa52.dc = aa67[5];if (aa52.lat!="" && aa52.lon!="") {aa65 = new GLatLng(aa52.lat,aa52.lon);aa70.setZoom(12);aa70.panTo(aa65);document.getElementById('haddress').style.color='blue';document.getElementById('haddress').innerHTML=aa04;aa15(aa65);GEvent.addListener(aa70, "click", aa14);

//var aa20 = "pub-0522741294342289";var aa06 = {maxAdsOnMap : 2,style: 'adunit',channel: '2777647679'};aa32 = new GAdsManager(aa70, aa20, aa06);aa32.enable();
}if (aa52.dc!="") {document.getElementById("dctitle").value = aa52.dc;document.getElementById("dctitle").style.backgroundColor='#d8ecf8';document.getElementById("dctitle").disabled = false;document.getElementById("dcan").checked = true;aa22 = true;}if (aa52.pn!="") {document.getElementById("ort").value = aa52.pn;}aa31(aa52.cc);}}
function aa08(aa36) {aa70.clearOverlays();if (!aa36 || aa36.Status.code != 200) {document.getElementById('haddress').style.color='red';document.getElementById('haddress').innerHTML=aa01;} else {var aa57 = aa36.Placemark[0];if (aa57.AddressDetails.Country) {if(aa57.AddressDetails.Country.CountryNameCode) {var aa21 = aa57.AddressDetails.Country.CountryNameCode;}if (aa57.AddressDetails.Country.Locality) {if (aa57.AddressDetails.Country.Locality.LocalityName) {var aa37 = aa57.AddressDetails.Country.Locality.LocalityName;}}if (aa57.AddressDetails.Country.SubAdministrativeArea) {if (aa57.AddressDetails.Country.SubAdministrativeArea.Locality) {if (aa57.AddressDetails.Country.SubAdministrativeArea.Locality.LocalityName) {var aa37 = aa57.AddressDetails.Country.SubAdministrativeArea.Locality.LocalityName;}}}if (aa57.AddressDetails.Country.AdministrativeArea) {if (aa57.AddressDetails.Country.AdministrativeArea.AdministrativeAreaName) {var aa59 = aa57.AddressDetails.Country.AdministrativeArea.AdministrativeAreaName;}if (aa57.AddressDetails.Country.AdministrativeArea.Locality) {if (aa57.AddressDetails.Country.AdministrativeArea.Locality.LocalityName) {var aa37 = aa57.AddressDetails.Country.AdministrativeArea.Locality.LocalityName;}}if (aa57.AddressDetails.Country.AdministrativeArea.SubAdministrativeArea) {if (aa57.AddressDetails.Country.AdministrativeArea.SubAdministrativeArea.Locality) {if (aa57.AddressDetails.Country.AdministrativeArea.SubAdministrativeArea.Locality.LocalityName) {var aa37 = aa57.AddressDetails.Country.AdministrativeArea.SubAdministrativeArea.Locality.LocalityName;}}}}}if (aa57.Point.coordinates) {var aa44 = aa57.Point.coordinates[1];var aa45 = aa57.Point.coordinates[0];}if (aa57.AddressDetails.Accuracy) {var aa13 = aa57.AddressDetails.Accuracy;}aa65 = new GLatLng(aa44,aa45);aa70.setZoom(aa13+7);aa70.panTo(aa65);document.getElementById('haddress').style.color='blue';document.getElementById('haddress').innerHTML=aa04;aa15(aa65);GEvent.addListener(aa70, "click", aa14);
//var aa20 = "pub-0522741294342289";var aa06 = {maxAdsOnMap : 2,style: 'adunit',channel: '2777647679'};aa32 = new GAdsManager(aa70, aa20, aa06);aa32.enable();
if (aa37) {aa52.pn=aa37;} else {aa52.pn="";}document.getElementById("ort").value = aa52.pn;if (aa59) {aa52.rc=aa59;} else {aa52.rc="";}
if (aa21) {aa31(aa21);}else {for(var i=0;i<document.georegion.land.options.length;i++) {if (document.georegion.land.options[i].text == aa57.address) {aa21 = document.georegion.land.options[i].value;break;}}aa31(aa21);}}}
function showAddress(aa42) {aa41.getLocations(aa42, aa08);}
function aa02() {var ua;if(window.XMLHttpRequest) {try {ua = new XMLHttpRequest();} catch(e) {ua = false;}} else if(window.ActiveXObject) {try {ua = new ActiveXObject("Microsoft.XMLHTTP");} catch(e) {ua = false;}}return ua;}
function aa33() {url="codexml.php?cc=all";aa21.open('GET', url, true);aa21.onreadystatechange = aa26;aa21.send(null);}
function aa26() {if(aa21.readyState == 4){if (aa21.status == 200) {var aa43 = aa21.responseXML.documentElement.getElementsByTagName("land");if (aa43.length > 0) {for (var i = 0; i < aa43.length; i++) {var aa63 = aa43[i].getAttribute("name");var aa62 = aa43[i].getAttribute("code");document.georegion.land.options[i] =new Option(aa63, aa62);}}if (aa52.cc != "") {aa31(aa52.cc);}}}}
function aa38(aa61) {if (aa61 && aa09 == aa61) {return;}if (aa61 && aa16 == aa61) {aa39();} else {aa09=aa61;document.georegion.region.options.length = 0;document.getElementById("regionalcode").value = "";var url="codexml.php?cc="+aa61.toLowerCase();aa30.open('GET', url, true);aa30.onreadystatechange = aa29;aa30.send(null);}}
function aa29() {if(aa30.readyState == 4){if (aa30.status == 200) {var aa46 = aa30.responseXML.documentElement.getElementsByTagName("region");if (aa46.length > 0) {for (var i = 0; i < aa46.length; i++) {if (aa46[i].getAttribute("name")) {var aa66 = aa46[i].getAttribute("name");} else{var aa66 ="";}if (aa46[i].getAttribute("code")) {var aa59 = aa46[i].getAttribute("code");} else{var aa59 ="";}document.georegion.region.options[i] =new Option(aa66, aa59);}aa16=aa09;}aa09="";aa39();}}}
function aa27() {if (aa52.order && !aa52.aa68) {aa52.aa68=true;aa52.order=false;aa49="cc="+aa52.cc+"&rc="+aa52.rc+"&pn="+aa52.pn+"&lat="+aa52.lat+"&lon="+aa52.lon+"&dc="+aa52.dc;url="geo.php";aa50.open('POST', url, true);aa50.onreadystatechange = aa24;aa50.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");aa50.send(aa49);}}
function aa24() {if(aa50.readyState == 4){if (aa50.status == 200) {var aa34 = aa50.responseText;document.getElementById('xhtmlcode').value = aa34;document.getElementById('hcode').innerHTML=aa18;}aa52.aa68=false;aa27();}}
function markieren() {document.getElementById('xhtmlcode').focus();document.getElementById('xhtmlcode').select();var aa49="l="+window.location.href+"; "+aa52.cc+"; "+aa52.rc+"; "+aa52.lat+"; "+aa52.lon+"; "+aa52.pn+"; "+document.getElementById("address").value+"; "+aa52.dc;url="abschluss.php";aa55.open('POST', url, true);aa55.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");aa55.send(aa49);}
function selectland(aa61) {aa52.cc=aa61;document.getElementById("laendercode").value = aa61;if (document.georegion.land.selectedIndex > 0) {document.getElementById('hland').innerHTML=aa19;} else {document.getElementById('hland').innerHTML=aa10;}aa52.rc="";document.getElementById("regionalcode").value = "";if (!aa52.lat) {var cname=document.georegion.land.options[document.georegion.land.selectedIndex].text;document.getElementById("address").value = cname;showAddress(cname);} else {aa38(aa61);aa52.order=true;aa27();}}
function selectregion(aa59) {document.getElementById("regionalcode").value = aa59;if (document.georegion.region.options.length > 1) {if (document.georegion.region.selectedIndex > 0) {document.getElementById('hregion').innerHTML=aa11;} else {document.getElementById('hregion').innerHTML=aa07;}} else {document.getElementById('hregion').innerHTML=aa05;}if (aa59 == "??") {aa59="";}aa52.rc=aa59;aa52.order=true;aa27();}
function selectgenau(aa58){aa23 = aa58;aa52.lat = aa51(aa52.aa54);aa52.lon = aa51(aa52.aa56);document.getElementById("lati").value = aa52.lat;document.getElementById("longi").value = aa52.lon;aa52.order=true;aa27();}
function newdcan(aa53) {aa22 = aa53;var aa64 = aa52.dc;if (aa53) {aa52.dc = document.getElementById("dctitle").value;document.getElementById("dctitle").style.backgroundColor='#d8ecf8';document.getElementById("dctitle").disabled = false;} else {aa52.dc = "";document.getElementById("dctitle").style.backgroundColor='#c0e1f3';document.getElementById("dctitle").disabled = true;}if (aa64 != aa52.dc) {aa52.order=true;aa27();}}
function newdc(aa64) {aa52.dc = aa64;aa52.order=true;aa27();}
function	aa31(aa61) {aa52.cc=aa61;aa38(aa61);document.getElementById("laendercode").value = aa61;var aa35 = true;for(var i=0;i<document.georegion.land.options.length;i++) {if (document.georegion.land.options[i].value == aa61) {document.georegion.land.selectedIndex = i;document.getElementById('hland').innerHTML=aa19;aa35 = false;break;}}if (aa35) {document.georegion.land.selectedIndex = 0;document.getElementById('hland').innerHTML=aa10;}}
function	aa39() {var aa35 = true;if (aa52.rc) {for(var i=0;i<document.georegion.region.options.length;i++) {if ((document.georegion.region.options[i].value == aa52.rc)||(document.georegion.region.options[i].text == aa52.rc)) {document.georegion.region.selectedIndex = i;aa52.rc = document.georegion.region.options[i].value;document.getElementById("regionalcode").value = aa52.rc;document.getElementById('hregion').innerHTML=aa11;aa35 = false;break;}}}if (aa35 && aa52.pn) {for(var i=0;i<document.georegion.region.options.length;i++) {if (document.georegion.region.options[i].text == aa52.pn) {document.georegion.region.selectedIndex = i;aa52.rc = document.georegion.region.options[i].value;document.getElementById("regionalcode").value = aa52.rc;document.getElementById('hregion').innerHTML=aa11;aa35 = false;break;}}}if (aa35) {document.georegion.region.selectedIndex = 0;aa52.rc="";document.getElementById("regionalcode").value = "";document.getElementById('hregion').innerHTML=aa05;}aa52.order=true;aa27();}
function newland(aa61) {aa31(aa61.toUpperCase());}
function newregion(aa59) {aa52.rc = aa59.toUpperCase();var aa35 = true;for(var i=0;i<document.georegion.region.options.length;i++) {if ((document.georegion.region.options[i].value == aa52.rc)||(document.georegion.region.options[i].text == aa52.rc)) {document.georegion.region.selectedIndex = i;aa52.rc = document.georegion.region.options[i].value;document.getElementById("regionalcode").value = aa52.rc;document.getElementById('hregion').innerHTML=aa11;aa35 = false;break;}}if (aa35) {document.georegion.region.selectedIndex = 0;document.getElementById("regionalcode").value = aa52.rc;document.getElementById('hregion').innerHTML=aa05;}aa52.order=true;aa27();}
function newort(aa63) {aa52.pn=aa63;aa52.order=true;aa27();}
function aa51(aa72) {return(Math.round(aa72*aa23)/aa23);}
function aa14(aa12,aa65) {if (aa12) {} else {aa15(aa65);aa52.order=true;aa27();}}
function aa17() {GEvent.clearListeners(aa28, "dragend");GEvent.clearListeners(aa28, "drag");GEvent.clearListeners(aa28, "dragstart");aa70.removeOverlay(aa28);}
function aa15(aa65) {if (aa28) {aa17();}aa28 = new GMarker(aa65, {draggable: true});GEvent.addListener(aa28,"dragstart",function() {aa70.closeInfoWindow();});GEvent.addListener(aa28,"drag",function() {document.getElementById("lati").value = aa51(aa28.getPoint().lat());document.getElementById("longi").value = aa51(aa28.getPoint().lng());});GEvent.addListener(aa28,"dragend",function() {aa52.aa54 = aa28.getPoint().lat();aa52.aa56 = aa28.getPoint().lng();aa52.lat = aa51(aa52.aa54);aa52.lon = aa51(aa52.aa56);aa52.order=true;aa27();});aa70.addOverlay(aa28);aa28.enableDragging();aa52.aa54 = aa28.getPoint().lat();aa52.aa56 = aa28.getPoint().lng();aa52.lat = aa51(aa52.aa54);aa52.lon = aa51(aa52.aa56);document.getElementById("lati").value = aa52.lat;document.getElementById("longi").value = aa52.lon;}